# Generated by Django 4.1.2 on 2022-10-17 16:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('street_line1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('street_line2', models.CharField(blank=True, max_length=100, verbose_name='Address 2')),
                ('zipcode', models.CharField(blank=True, max_length=6, verbose_name='ZIP Code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='State')),
            ],
        ),
    ]
